version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: baked-potato-db
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: baked_potatos

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d baked_potatos"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: ./api

    container_name: baked-potato-api

    depends_on:
      postgres:
        condition: service_healthy

    ports:
      - "8080:8080"

    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: docker
      DB_NAME: baked_potatos

  frontend:
    build: "./ui/interface"

    container_name: baked-potato-ui

    ports:
      - "5173:5173"

    depends_on:
      - api

volumes:
  postgres-data:
